// src/components/contest/ContestDayGroup.tsx
import { useMemo } from 'react';
import { ChevronDown } from 'lucide-react';
import { cn } from '@/lib/utils';
import { ContestCard } from './ContestCard';
import type { Contest } from '@/types';

interface ContestDayGroupProps {
  title: string;
  contests: Contest[];
  now: number;
  selectedPlatforms: Record<string, boolean>;
  isFavorite: (contest: Contest) => boolean;
  getPlatformImage: (platform: string) => string;
  variant?: 'today' | 'tomorrow' | 'future' | 'history';
  collapsible?: boolean;
  expanded?: boolean;
  onToggle?: () => void;
  onOpenContest: (contest: Contest) => void;
  onToggleFavorite: (contest: Contest) => void;
}

export function ContestDayGroup({
  title,
  contests,
  now,
  selectedPlatforms,
  isFavorite,
  getPlatformImage,
  variant,
  collapsible,
  expanded,
  onToggle,
  onOpenContest,
  onToggleFavorite,
}: ContestDayGroupProps) {
  const visibleContests = useMemo(
    () => contests.filter((c) => selectedPlatforms[c.platform]),
    [contests, selectedPlatforms],
  );

  const visibleCount = visibleContests.length;

  return (
    <div className="mb-3">
      {/* Collapsible header */}
      {collapsible && (
        <div className="mb-2">
          <div
            className="flex cursor-pointer select-none items-center gap-2 rounded-[var(--radius-sm)] border border-[var(--card-border)] bg-[var(--card-bg)] px-5 py-3 shadow-[var(--card-shadow)] transition-all hover:bg-[rgba(255,161,22,0.08)]"
            onClick={onToggle}
          >
            <span
              className={cn(
                'text-[15px] font-[620]',
                variant === 'history' ? 'text-[var(--color-text-soft)]' : 'text-[var(--color-text)]',
              )}
            >
              {title}
            </span>
            <span className="text-[13px] text-[var(--color-text-muted)]">({visibleCount} 场)</span>
            <ChevronDown
              size={18}
              className={cn(
                'ml-auto flex-shrink-0 text-[var(--color-text-muted)] transition-transform duration-[var(--motion-base)]',
                expanded && 'rotate-180',
              )}
            />
          </div>
        </div>
      )}

      {/* Content card */}
      {(!collapsible || expanded) && (
        <div className="relative overflow-hidden rounded-[var(--radius-lg)] border border-[var(--card-border)] bg-[var(--card-bg)] shadow-[var(--card-shadow)] backdrop-blur-sm">
          {/* Gradient border effect */}
          <div className="pointer-events-none absolute inset-0 rounded-[var(--radius-lg)] bg-[linear-gradient(180deg,rgba(255,161,22,0.14),rgba(20,184,166,0.08))]" style={{ padding: '1px', mask: 'linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0)', WebkitMask: 'linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0)', WebkitMaskComposite: 'xor', maskComposite: 'exclude' }} />

          {!collapsible && (
            <div className="border-b border-[var(--card-divider)] px-5 py-3">
              <span className="text-[15px] font-[620] text-[var(--color-text)]">{title}</span>
            </div>
          )}

          {visibleCount === 0 && collapsible ? (
            <div className="p-5 text-center text-sm text-[var(--color-text-muted)]">这里没有比赛喵~</div>
          ) : (
            <div>
              {visibleContests.map((contest, idx) => (
                <div key={idx}>
                  <ContestCard
                    contest={contest}
                    now={now}
                    isFavorite={isFavorite(contest)}
                    platformImage={getPlatformImage(contest.platform)}
                    onOpen={onOpenContest}
                    onToggleFavorite={onToggleFavorite}
                  />
                  {idx < visibleContests.length - 1 && (
                    <div className="mx-0 h-px bg-[var(--card-divider)]" />
                  )}
                </div>
              ))}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// src/components/contest/ContestDayGroup.vue
<template>
  <div class="day-group" :class="`day-group--${variant}`">
    <!-- Collapsible header for future/history days -->
    <div v-if="collapsible" class="day-group-header">
      <n-card :bordered="true" class="day-card day-card--collapsible" :class="{ 'day-card--history': variant === 'history' }" :content-style="{ padding: '0' }">
        <template #header>
          <div class="day-header-content" @click="$emit('toggle')">
            <span class="day-title" :class="{ 'day-title--history': variant === 'history' }">{{ title }}</span>
            <span class="day-count">({{ visibleCount }} 场)</span>
            <n-icon class="expand-icon" :class="{ 'is-expanded': expanded }">
              <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                <polyline points="6 9 12 15 18 9"></polyline>
              </svg>
            </n-icon>
          </div>
        </template>
      </n-card>
    </div>

    <!-- Non-collapsible header (today/tomorrow) -->
    <n-card
      v-if="!collapsible || expanded"
      :bordered="true"
      class="day-card"
      :class="{ 'day-card--content': collapsible, 'day-card--history-content': variant === 'history' }"
      :content-style="{ padding: '0' }"
    >
      <template v-if="!collapsible" #header>
        <span class="day-title">{{ title }}</span>
      </template>

      <div v-if="visibleCount === 0 && collapsible" class="no-contest">这里没有比赛喵~</div>
      <div v-else>
        <template v-for="(contest, idx) in contests" :key="idx">
          <contest-card
            v-if="selectedPlatforms[contest.platform]"
            :contest="contest"
            :now="now"
            :is-favorite="isFavorite(contest)"
            :platform-image="getPlatformImage(contest.platform)"
            @open="$emit('open-contest', $event)"
            @toggle-favorite="$emit('toggle-favorite', $event)"
          />
          <n-divider v-if="idx < contests.length - 1 && selectedPlatforms[contests[idx + 1]?.platform]" />
        </template>
      </div>
    </n-card>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { NCard, NIcon, NDivider } from 'naive-ui';
import ContestCard from './ContestCard.vue';
import type { Contest } from '../../types';

const props = defineProps<{
  title: string;
  contests: Contest[];
  now: number;
  selectedPlatforms: Record<string, boolean>;
  isFavorite: (contest: Contest) => boolean;
  getPlatformImage: (platform: string) => string;
  variant?: 'today' | 'tomorrow' | 'future' | 'history';
  collapsible?: boolean;
  expanded?: boolean;
}>();

defineEmits<{
  toggle: [];
  'open-contest': [contest: Contest];
  'toggle-favorite': [contest: Contest];
}>();

const visibleCount = computed(() =>
  props.contests.filter((c) => props.selectedPlatforms[c.platform]).length,
);
</script>

<style scoped>
.day-group {
  margin-bottom: var(--space-3);
}

.day-group-header {
  margin-bottom: var(--space-2);
}

.day-card {
  border: 1px solid var(--card-border) !important;
  border-radius: var(--radius-lg);
  background: var(--card-bg);
  box-shadow: var(--card-shadow);
  position: relative;
  overflow: hidden;
  backdrop-filter: blur(8px);
  -webkit-backdrop-filter: blur(8px);
  transition: transform var(--motion-base) var(--motion-ease), box-shadow var(--motion-base) var(--motion-ease);
}

.day-card::before {
  content: '';
  position: absolute;
  inset: 0;
  border-radius: var(--radius-lg);
  padding: 1px;
  background: linear-gradient(180deg, rgba(14, 165, 233, 0.14), rgba(52, 211, 153, 0.08));
  -webkit-mask: linear-gradient(#000 0 0) content-box, linear-gradient(#000 0 0);
  -webkit-mask-composite: xor;
  mask-composite: exclude;
  pointer-events: none;
}

.day-card:hover:not(.day-card--collapsible) {
  transform: translateY(-2px);
  box-shadow: var(--card-shadow-hover);
}

.day-card--collapsible .day-header-content {
  display: flex;
  align-items: center;
  gap: var(--space-2);
  cursor: pointer;
  user-select: none;
  padding: 4px;
  margin: -4px;
  border-radius: var(--radius-sm);
  transition: all var(--motion-base) var(--motion-ease);
}

.day-card--collapsible .day-header-content:hover {
  background: rgba(14, 165, 233, 0.08);
}

.expand-icon {
  width: 18px;
  height: 18px;
  margin-left: auto;
  color: var(--color-text-muted);
  transition: transform var(--motion-base) var(--motion-ease);
  flex-shrink: 0;
}

.expand-icon.is-expanded {
  transform: rotate(180deg);
}

.day-title {
  font-size: 15px;
  font-weight: 620;
  color: var(--color-text);
}

.day-title--history {
  color: var(--color-text-soft);
}

.day-count {
  font-size: 13px;
  color: var(--color-text-muted);
}

.no-contest {
  padding: 20px;
  text-align: center;
  font-size: 14px;
  color: var(--color-text-muted);
}

.day-card :deep(.n-card__content),
.day-card :deep(.n-card__header) {
  background: transparent;
}

.day-card :deep(.n-card-header__main) {
  color: var(--color-text-soft);
}

.day-card :deep(.n-divider) {
  margin: 0;
  background-color: var(--card-divider);
}

.day-card :deep(.n-tag) {
  border-radius: 999px;
}

.day-card :deep(.n-button.n-button--primary-type.n-button--ghost) {
  border-color: rgba(14, 165, 233, 0.28);
  color: var(--color-primary);
}

.day-card :deep(.n-button.n-button--primary-type.n-button--ghost:hover) {
  border-color: rgba(14, 165, 233, 0.42);
  background-color: rgba(14, 165, 233, 0.08);
}

@media (prefers-reduced-motion: reduce) {
  .day-card {
    animation: fade-only 140ms ease-out both !important;
    transition-duration: 0.01ms !important;
  }

  .expand-icon.is-expanded {
    transform: none;
  }
}

@keyframes fade-only {
  from { opacity: 0; }
  to { opacity: 1; }
}
</style>
