// src/components/contest/ContestCard.vue
<template>
  <div class="contest-card" :class="[`contest-card--${state}`]">
    <div class="platform-icon">
      <img :src="platformImage" :alt="contest.platform" />
    </div>
    <div
      class="contest-info"
      role="button"
      tabindex="0"
      @click="$emit('open', contest)"
      @keydown.enter.prevent="$emit('open', contest)"
      @keydown.space.prevent="$emit('open', contest)"
    >
      <div class="contest-name">{{ contest.name }}</div>
      <div class="contest-meta">
        <span class="contest-time">{{ contest.startHourMinute }} - {{ contest.endHourMinute }}</span>
        <n-tag size="small" :type="stateType">{{ stateLabel }}</n-tag>
        <n-tag v-if="countdown" type="success" size="small" class="countdown-tag">
          {{ countdown }}
        </n-tag>
      </div>
    </div>
    <div class="contest-action">
      <n-button size="small" type="primary" ghost @click.stop="$emit('open', contest)">参赛</n-button>
      <n-button quaternary circle @click.stop="$emit('toggle-favorite', contest)">
        <template #icon>
          <n-icon :size="24" :color="isFavorite ? 'var(--color-warning)' : undefined">
            <star-outlined v-if="!isFavorite" />
            <star-filled v-else />
          </n-icon>
        </template>
      </n-button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { NButton, NIcon, NTag } from 'naive-ui';
import { StarOutlined, StarFilled } from '@vicons/material';
import type { Contest } from '../../types';

const props = defineProps<{
  contest: Contest;
  now: number;
  isFavorite: boolean;
  platformImage: string;
}>();

defineEmits<{
  open: [contest: Contest];
  'toggle-favorite': [contest: Contest];
}>();

type ContestState = 'upcoming' | 'running' | 'ended';

const state = computed<ContestState>(() => {
  const start = props.contest.startTimeSeconds * 1000;
  const end = start + props.contest.durationSeconds * 1000;
  if (props.now < start) return 'upcoming';
  if (props.now >= start && props.now <= end) return 'running';
  return 'ended';
});

const stateLabel = computed(() => {
  if (state.value === 'upcoming') return '即将开始';
  if (state.value === 'running') return '进行中';
  return '已结束';
});

const stateType = computed(() => {
  if (state.value === 'upcoming') return 'info';
  if (state.value === 'running') return 'success';
  return 'default';
});

const countdown = computed(() => {
  if (!props.contest.startTimeSeconds) return null;
  const diff = props.contest.startTimeSeconds * 1000 - props.now;
  if (diff <= 0 || diff > 24 * 60 * 60 * 1000) return null;
  const hours = Math.floor(diff / (1000 * 60 * 60));
  const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
  return `${hours}小时${minutes}分后`;
});
</script>

<style scoped>
.contest-card {
  display: flex;
  align-items: center;
  padding: 12px 16px;
  position: relative;
}

.contest-card::before {
  content: '';
  position: absolute;
  left: 0;
  top: 10px;
  bottom: 10px;
  width: 3px;
  border-radius: 999px;
  background: rgba(148, 163, 184, 0.45);
}

.contest-card--upcoming::before {
  background: rgba(14, 165, 233, 0.7);
}

.contest-card--running::before {
  background: rgba(52, 211, 153, 0.78);
}

.contest-card--ended::before {
  background: rgba(148, 163, 184, 0.62);
}

.platform-icon img {
  width: 32px;
  height: 32px;
  border-radius: 8px;
  border: 1px solid var(--color-border);
}

.contest-info {
  flex: 1;
  margin-left: 14px;
  cursor: pointer;
  border-radius: var(--radius-sm);
}

.contest-info:focus-visible {
  outline: none;
  box-shadow: var(--focus-ring);
}

.contest-name {
  font-size: 14px;
  font-weight: 610;
  margin-bottom: 4px;
  color: var(--color-text);
}

.contest-meta {
  display: flex;
  align-items: center;
  gap: 8px;
  flex-wrap: wrap;
}

.contest-time {
  font-size: 12px;
  color: var(--color-text-muted);
}

.contest-action {
  display: flex;
  align-items: center;
  gap: 6px;
  flex-shrink: 0;
}

@media (max-width: 768px) {
  .contest-card {
    padding: 12px;
  }

  .contest-name {
    font-size: 13px;
  }
}
</style>

// src/components/contest/ContestCard.tsx
import { useMemo } from 'react';
import { Star } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Button } from '@/components/ui/button';
import type { Contest } from '@/types';

type ContestState = 'upcoming' | 'running' | 'ended';

interface ContestCardProps {
  contest: Contest;
  now: number;
  isFavorite: boolean;
  platformImage: string;
  onOpen: (contest: Contest) => void;
  onToggleFavorite: (contest: Contest) => void;
}

export function ContestCard({
  contest,
  now,
  isFavorite,
  platformImage,
  onOpen,
  onToggleFavorite,
}: ContestCardProps) {
  const state = useMemo<ContestState>(() => {
    const start = contest.startTimeSeconds * 1000;
    const end = start + contest.durationSeconds * 1000;
    if (now < start) return 'upcoming';
    if (now >= start && now <= end) return 'running';
    return 'ended';
  }, [contest.startTimeSeconds, contest.durationSeconds, now]);

  const stateLabel = state === 'upcoming' ? '即将开始' : state === 'running' ? '进行中' : '已结束';

  const stateColorClass =
    state === 'upcoming'
      ? 'bg-[rgba(255,161,22,0.7)]'
      : state === 'running'
        ? 'bg-[rgba(20,184,166,0.78)]'
        : 'bg-[rgba(148,163,184,0.62)]';

  const tagClass =
    state === 'upcoming'
      ? 'bg-[rgba(255,161,22,0.1)] text-[var(--color-primary)]'
      : state === 'running'
        ? 'bg-[rgba(20,184,166,0.1)] text-[var(--color-success)]'
        : 'bg-[var(--color-surface-muted)] text-[var(--color-text-muted)]';

  const countdown = useMemo(() => {
    if (!contest.startTimeSeconds) return null;
    const diff = contest.startTimeSeconds * 1000 - now;
    if (diff <= 0 || diff > 24 * 60 * 60 * 1000) return null;
    const hours = Math.floor(diff / (1000 * 60 * 60));
    const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    return `${hours}小时${minutes}分后`;
  }, [contest.startTimeSeconds, now]);

  return (
    <div className="relative flex items-center px-4 py-3">
      <div className={cn('absolute left-0 top-2.5 bottom-2.5 w-[3px] rounded-full', stateColorClass)} />
      <div className="h-8 w-8 flex-shrink-0 overflow-hidden rounded-lg border border-[var(--color-border)]">
        <img src={platformImage} alt={contest.platform} className="h-full w-full object-cover" />
      </div>
      <div
        className="ml-3.5 flex-1 cursor-pointer rounded-[var(--radius-sm)]"
        role="button"
        tabIndex={0}
        onClick={() => onOpen(contest)}
        onKeyDown={(e) => {
          if (e.key === 'Enter' || e.key === ' ') {
            e.preventDefault();
            onOpen(contest);
          }
        }}
      >
        <div className="mb-1 text-sm font-[610] text-[var(--color-text)]">{contest.name}</div>
        <div className="flex flex-wrap items-center gap-2">
          <span className="text-xs text-[var(--color-text-muted)]">
            {contest.startHourMinute} - {contest.endHourMinute}
          </span>
          <span className={cn('rounded-full px-2 py-0.5 text-xs', tagClass)}>{stateLabel}</span>
          {countdown && (
            <span className="rounded-full bg-[rgba(20,184,166,0.1)] px-2 py-0.5 text-xs text-[var(--color-success)]">
              {countdown}
            </span>
          )}
        </div>
      </div>
      <div className="flex flex-shrink-0 items-center gap-1.5">
        <Button
          size="sm"
          variant="outline"
          onClick={() => onOpen(contest)}
          className="border-[rgba(255,161,22,0.28)] text-[var(--color-primary)] hover:bg-[rgba(255,161,22,0.08)]"
        >
          参赛
        </Button>
        <button
          onClick={() => onToggleFavorite(contest)}
          className="flex h-8 w-8 items-center justify-center rounded-full transition-colors hover:bg-[var(--color-surface-muted)]"
        >
          <Star
            size={20}
            className={cn(
              'transition-colors',
              isFavorite ? 'fill-[var(--color-warning)] text-[var(--color-warning)]' : 'text-[var(--color-text-muted)]',
            )}
          />
        </button>
      </div>
    </div>
  );
}
