// src/views/SolvedNumPage.tsx
import { useState, useEffect, useCallback } from 'react';
import { Search, RefreshCw, PieChart, HelpCircle, X } from 'lucide-react';
import { PageHeader } from '@/components/PageHeader';
import { SolvedNumService } from '@/services/solved';
import { Button } from '@/components/ui/button';
import { ContestService } from '@/services/contest';

interface PlatformConfig {
  name: string;
  shortName: string;
  color: string;
  labelField: string;
}

const PLATFORMS: PlatformConfig[] = [
  { name: 'Codeforces', shortName: 'CF', color: '#4080ff', labelField: '用户名' },
  { name: 'AtCoder', shortName: 'AtC', color: '#66b2ff', labelField: '用户名' },
  { name: '力扣', shortName: '力扣', color: '#9966ff', labelField: '用户名' },
  { name: '洛谷', shortName: '洛谷', color: '#32cd32', labelField: '用户名' },
  { name: '牛客', shortName: '牛客', color: '#ff6600', labelField: 'id' },
  { name: 'VJudge', shortName: 'VJ', color: '#ffa500', labelField: '用户名' },
  { name: 'HDU', shortName: 'HDU', color: '#969696', labelField: '用户名' },
  { name: 'POJ', shortName: 'POJ', color: '#c8c8c8', labelField: '用户名' },
  { name: '蓝桥云课', shortName: '蓝桥', color: '#ffd700', labelField: 'id' },
  { name: 'QOJ', shortName: 'QOJ', color: '#ff1493', labelField: '用户名' },
];

const images: Record<string, string> = {
  Codeforces: new URL('../assets/platforms/Codeforces.jpg', import.meta.url).href,
  AtCoder: new URL('../assets/platforms/AtCoder.jpg', import.meta.url).href,
  '力扣': new URL('../assets/platforms/LeetCode.jpg', import.meta.url).href,
  '洛谷': new URL('../assets/platforms/Luogu.jpg', import.meta.url).href,
  '牛客': new URL('../assets/platforms/Nowcoder.jpg', import.meta.url).href,
  VJudge: new URL('../assets/platforms/VJudge.jpg', import.meta.url).href,
  HDU: new URL('../assets/platforms/HDU.jpg', import.meta.url).href,
  POJ: new URL('../assets/platforms/POJ.jpg', import.meta.url).href,
  '蓝桥云课': new URL('../assets/platforms/Lanqiao.jpg', import.meta.url).href,
  QOJ: new URL('../assets/platforms/QOJ.jpg', import.meta.url).href,
};

const STORAGE_KEY = 'solved_usernames';

function loadSavedUsernames(): Record<string, string> {
  try {
    const raw = localStorage.getItem(STORAGE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
}

function saveUsernames(data: Record<string, string>) {
  try {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
  } catch {
    // ignore
  }
}

function PlatformCard({
  config,
  onRefresh,
  onQueryAll,
}: {
  config: PlatformConfig;
  onRefresh: (platform: string) => void;
  onQueryAll: (platform: string) => void;
}) {
  const [username, setUsername] = useState(() => loadSavedUsernames()[config.name] || '');
  const [result, setResult] = useState<{ solved: number; info: string } | null>(null);
  const [loading, setLoading] = useState(false);

  const save = useCallback((value: string) => {
    setUsername(value);
    const all = loadSavedUsernames();
    all[config.name] = value;
    saveUsernames(all);
  }, [config.name]);

  const query = useCallback(async (userOverride?: string) => {
    const u = userOverride ?? username;
    if (!u.trim()) return;
    setLoading(true);
    setResult(null);
    try {
      // Support multi-user with ; separator
      const users = u.split(';').map((s) => s.trim()).filter(Boolean);
      let totalSolved = 0;
      for (const user of users) {
        const data = await SolvedNumService.getSolvedNum(config.name, user);
        totalSolved += (data as { solvedNum: number }).solvedNum || 0;
      }
      const info = users.length > 1
        ? `总解题数: ${totalSolved} (${users.length}个用户)`
        : `已解决: ${totalSolved}`;
      setResult({ solved: totalSolved, info });
    } catch {
      setResult({ solved: 0, info: '查询失败，请检查网络或用户名是否正确' });
    } finally {
      setLoading(false);
    }
  }, [config.name, username]);

  // Listen for query-all from parent
  useEffect(() => {
    const handler = (e: CustomEvent) => {
      if (e.detail === config.name) query();
    };
    window.addEventListener('solved-query-all', handler as EventListener);
    return () => window.removeEventListener('solved-query-all', handler as EventListener);
  }, [config.name, query]);

  const hasSpecialHelp = config.name === '牛客' || config.name === '蓝桥云课';

  return (
    <div className="relative overflow-hidden rounded-[var(--radius-lg)] border border-[var(--card-border)] bg-[var(--card-bg)] shadow-[var(--card-shadow)]">
      {/* Header */}
      <div className="flex items-center gap-2 border-b border-[var(--card-divider)] bg-[rgba(211,218,220,0.3)] px-3 py-2">
        <img src={images[config.name]} alt={config.name} className="h-7 w-7 rounded-md border border-[var(--color-border)]" />
        <span className="text-sm font-bold text-[var(--color-text)]">{config.name}</span>
        <div className="flex-1" />
        {hasSpecialHelp && (
          <button
            onClick={() => {
              if (config.name === '牛客') ContestService.openUrl('https://ac.nowcoder.com/acm/home');
              else ContestService.openUrl('https://www.lanqiao.cn/users/');
            }}
            className="flex h-7 w-7 items-center justify-center rounded-full text-[var(--color-text-muted)] hover:bg-[var(--nav-hover-bg)] hover:text-[var(--color-primary)]"
          >
            <HelpCircle size={16} />
          </button>
        )}
        <button
          onClick={() => query()}
          disabled={loading}
          className="flex h-7 w-7 items-center justify-center rounded-full text-[var(--color-text-muted)] hover:bg-[var(--nav-hover-bg)] hover:text-[var(--color-primary)]"
        >
          <RefreshCw size={16} className={loading ? 'animate-spin' : ''} />
        </button>
      </div>

      {/* Input */}
      <div className="px-3 pt-3">
        <div className="relative">
          <input
            type="text"
            value={username}
            onChange={(e) => {
              save(e.target.value);
              setResult(null);
            }}
            disabled={loading}
            placeholder={config.name === '牛客' || config.name === '蓝桥云课' ? 'id' : '用户名'}
            className="w-full border-b border-[var(--color-border)] bg-transparent py-1.5 pr-8 text-sm text-[var(--color-text)] outline-none focus:border-[var(--color-primary)] disabled:opacity-50"
          />
          {username && !loading && (
            <button
              onClick={() => { save(''); setResult(null); }}
              className="absolute right-0 top-1/2 -translate-y-1/2 text-[var(--color-text-muted)] hover:text-[var(--color-text)]"
            >
              <X size={16} />
            </button>
          )}
        </div>
        <div className="mt-0.5 text-[11px] text-gray-400">多用户用;分隔</div>
      </div>

      {/* Body */}
      <div className="px-3 pb-3 pt-2">
        {loading && (
          <div className="flex items-center gap-2 py-1">
            <div className="h-1 flex-1 overflow-hidden rounded-full bg-[rgba(126,186,213,0.3)]">
              <div className="h-full animate-pulse rounded-full bg-[var(--color-primary)]" style={{ width: '60%' }} />
            </div>
          </div>
        )}

        {result && !loading && (
          <div
            className={`text-center text-sm ${
              result.info.includes('失败') ? 'text-[var(--color-error)]' : 'text-[var(--color-success)]'
            }`}
          >
            {result.info}
          </div>
        )}
      </div>
    </div>
  );
}

export default function SolvedNumPage() {
  const [pieData, setPieData] = useState<{ solved: number; total: number } | null>(null);

  const queryAll = useCallback(() => {
    for (const p of PLATFORMS) {
      window.dispatchEvent(new CustomEvent('solved-query-all', { detail: p.name }));
    }
  }, []);

  const showPieChart = useCallback(async () => {
    let totalSolved = 0;
    let platformCount = 0;
    const loaded = loadSavedUsernames();

    for (const p of PLATFORMS) {
      const u = loaded[p.name];
      if (!u?.trim()) continue;
      try {
        const users = u.split(';').map((s) => s.trim()).filter(Boolean);
        let sum = 0;
        for (const user of users) {
          const data = await SolvedNumService.getSolvedNum(p.name, user);
          sum += (data as { solvedNum: number }).solvedNum || 0;
        }
        if (sum > 0) {
          totalSolved += sum;
          platformCount++;
        }
      } catch {
        // skip
      }
    }

    if (totalSolved === 0 && platformCount === 0) {
      setPieData({ solved: 0, total: 0 });
    } else {
      setPieData({ solved: totalSolved, total: platformCount });
    }
  }, []);

  return (
    <div className="flex h-full flex-col bg-transparent">
      {/* App bar */}
      <PageHeader
        title="题数统计"
        actions={
          <>
            <button
              onClick={showPieChart}
              className="flex h-9 w-9 items-center justify-center rounded-full text-[var(--color-text-muted)] hover:bg-[var(--nav-hover-bg)] hover:text-[var(--color-primary)]"
            >
              <PieChart size={22} />
            </button>
            <button
              onClick={queryAll}
              className="flex h-9 w-9 items-center justify-center rounded-full text-[var(--color-text-muted)] hover:bg-[var(--nav-hover-bg)] hover:text-[var(--color-primary)]"
            >
              <Search size={22} />
            </button>
          </>
        }
      />

      {/* Grid */}
      <div className="flex-1 overflow-y-auto p-3">
        <div className="grid grid-cols-[repeat(auto-fill,minmax(300px,1fr))] gap-3 max-md:grid-cols-1">
          {PLATFORMS.map((p) => (
            <PlatformCard key={p.name} config={p} onRefresh={queryAll} onQueryAll={queryAll} />
          ))}
        </div>
      </div>

      {/* Pie chart modal */}
      {pieData && (
        <div className="fixed inset-0 z-50 flex items-center justify-center">
          <div className="absolute inset-0 bg-black/50" onClick={() => setPieData(null)} />
          <div className="relative z-10 w-full max-w-md rounded-[var(--radius-lg)] border border-[var(--color-border)] bg-[var(--color-surface)] p-6 shadow-xl">
            <h3 className="mb-4 text-center text-lg font-semibold text-[var(--color-text)]">解题统计</h3>
            {pieData.total === 0 ? (
              <div className="py-8 text-center text-[var(--color-text-muted)]">
                暂无数据，请先查询题目
              </div>
            ) : (
              <div className="text-center">
                <div className="mb-4 text-xl font-bold text-[var(--color-success)]">
                  总计：{pieData.solved}题
                </div>
                <div className="relative mx-auto h-64 w-64 rounded-full border-4 border-[var(--color-border)] bg-[var(--color-surface-muted)] flex items-center justify-center">
                  <div className="text-center">
                    <div className="text-2xl font-bold text-[var(--color-primary)]">{pieData.solved}</div>
                    <div className="text-xs text-[var(--color-text-muted)]">Total AC</div>
                  </div>
                </div>
              </div>
            )}
            <div className="mt-4 flex justify-center">
              <Button onClick={() => setPieData(null)}>关闭</Button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}

// src/views/SolvedNumPage.vue
<template>
  <div class="solved-page">
    <div class="app-bar">
      <h2>解题数量</h2>
      <div class="actions">
        <n-button quaternary circle @click="refreshAll">
          <template #icon>
            <n-icon :size="28"><search-outlined /></n-icon>
          </template>
        </n-button>
        <n-button quaternary circle @click="showStats = !showStats">
          <template #icon>
            <n-icon :size="28"><bar-chart-outlined /></n-icon>
          </template>
        </n-button>
      </div>
    </div>

    <transition name="slide-down">
      <StatsPanel 
        v-if="showStats" 
        :visible="showStats" 
        :data="statsData"
        @close="showStats = false"
      />
    </transition>

    <div class="content">
      <div 
        class="responsive-grid" 
        :style="{ 
          '--cols': gridCols,
          '--gap': '24px'
        }"
      >
        <div 
          v-for="platform in platforms" 
          :key="platform" 
          class="grid-item"
        >
          <n-card class="platform-card" :content-style="{ padding: '0' }">
            <div class="card-header">
              <img :src="getPlatformImage(platform)" class="platform-icon" />
              <span class="platform-name">{{ platform }}</span>
              <div class="spacer"></div>
              <n-button quaternary circle @click="querySolved(platform)">
                <template #icon>
                  <n-icon><refresh-outlined /></n-icon>
                </template>
              </n-button>
            </div>
            
            <div class="card-body">
              <n-input
                v-model:value="usernames[platform]"
                :placeholder="getPlaceholder(platform)"
                clearable
                @update:value="(v) => saveUsername(platform, v)"
                @keyup.enter="querySolved(platform)"
              >
              </n-input>
              
              <div class="status-area">
                <n-progress
                  v-if="loading[platform]"
                  type="line"
                  :percentage="undefined" 
                  processing
                  :show-indicator="false"
                  style="margin-top: 10px;"
                />
                
                <div v-if="messages[platform]" class="message" :class="{ error: isError[platform] }">
                  {{ messages[platform] }}
                </div>
              </div>
            </div>
          </n-card>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, reactive, onMounted, onUnmounted, computed } from 'vue';
import { NButton, NIcon, NCard, NInput, NProgress } from 'naive-ui';
import { SearchOutlined, RefreshOutlined, BarChartOutlined } from '@vicons/material';
import { SolvedNumService } from '../services/solved';
import StatsPanel from '../components/StatsPanel.vue';

const platforms = [
  'Codeforces', 'AtCoder', 'VJudge', 'HDU', 'POJ', '蓝桥', '洛谷', '牛客', '力扣'
];

const usernames = reactive<Record<string, string>>({});
const loading = reactive<Record<string, boolean>>({});
const messages = reactive<Record<string, string>>({});
const isError = reactive<Record<string, boolean>>({});
const solvedCounts = reactive<Record<string, number>>({});
const showStats = ref(false);
const gridCols = ref(3);

// Import images
const images: Record<string, string> = {
  'Codeforces': new URL('../assets/platforms/Codeforces.jpg', import.meta.url).href,
  'AtCoder': new URL('../assets/platforms/AtCoder.jpg', import.meta.url).href,
  'VJudge': new URL('../assets/platforms/VJudge.jpg', import.meta.url).href,
  'HDU': new URL('../assets/platforms/hdu.jpg', import.meta.url).href,
  'POJ': new URL('../assets/platforms/poj.jpg', import.meta.url).href,
  'QOJ': new URL('../assets/platforms/qoj.jpg', import.meta.url).href,
  '洛谷': new URL('../assets/platforms/Luogu.jpg', import.meta.url).href,
  '牛客': new URL('../assets/platforms/Nowcoder.jpg', import.meta.url).href,
  '力扣': new URL('../assets/platforms/LeetCode.jpg', import.meta.url).href,
  '蓝桥': new URL('../assets/platforms/Lanqiao.jpg', import.meta.url).href,
};

const getPlatformImage = (platform: string) => {
  return images[platform] || images['Other'];
};

const getPlaceholder = (platform: string) => {
  if (platform === '牛客') return '请输入ID';
  return '请输入用户名';
};

const statsData = computed(() => {
  return Object.keys(solvedCounts)
    .filter(p => solvedCounts[p] > 0)
    .map(p => ({ platform: p, count: solvedCounts[p] }));
});

// Responsive Grid Logic
const calculateCols = () => {
  const width = window.innerWidth;
  if (width >= 1300) {
    gridCols.value = 4;
  } else if (width >= 960) {
    gridCols.value = 3;
  } else if (width >= 480) {
    gridCols.value = 2;
  } else {
    gridCols.value = 1;
  }
};

const debounce = (fn: Function, delay: number) => {
  let timer: any = null;
  return (...args: any[]) => {
    if (timer) clearTimeout(timer);
    timer = setTimeout(() => {
      fn.apply(null, args);
    }, delay);
  };
};

const handleResize = debounce(calculateCols, 100);

onMounted(() => {
  platforms.forEach(p => {
    usernames[p] = localStorage.getItem(`solved_username_${p}`) || '';
    loading[p] = false;
    messages[p] = '';
    isError[p] = false;
    solvedCounts[p] = 0;
  });
  
  // Initial calculation
  calculateCols();
  window.addEventListener('resize', handleResize);
});

onUnmounted(() => {
  window.removeEventListener('resize', handleResize);
});

const saveUsername = (platform: string, username: string) => {
  localStorage.setItem(`solved_username_${platform}`, username);
  messages[platform] = ''; 
};

const querySolved = async (platform: string) => {
  const name = usernames[platform];
  if (!name) return;

  loading[platform] = true;
  messages[platform] = '';
  isError[platform] = false;

  try {
    const result = await SolvedNumService.getSolvedNum(platform, name);
    messages[platform] = `解题数: ${result.solvedNum}`;
    solvedCounts[platform] = result.solvedNum;
  } catch (e) {
    messages[platform] = '查询失败，请检查网络或用户名是否正确';
    isError[platform] = true;
    solvedCounts[platform] = 0;
  } finally {
    loading[platform] = false;
  }
};

const refreshAll = () => {
  platforms.forEach(p => {
    if (usernames[p]) {
      querySolved(p);
    }
  });
};
</script>

<style scoped>
.solved-page {
  display: flex;
  flex-direction: column;
  height: 100%;
  background-color: var(--color-surface);
  position: relative;
}

.app-bar {
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 0 16px;
  height: 64px;
  background-color: var(--color-surface);
  border-bottom: 1px solid var(--color-border);
}

.app-bar h2 {
  margin: 0;
  font-size: 20px;
}

.actions {
  display: flex;
  gap: 8px;
}

.content {
  flex: 1;
  padding: 16px;
  overflow-y: auto;
}

/* Responsive Grid Styles */
.responsive-grid {
  display: grid;
  grid-template-columns: repeat(var(--cols), 1fr);
  gap: var(--gap);
  width: 100%;
  transition: all 0.3s ease; /* Transition for grid changes (though tracks animate poorly, content does) */
}

.grid-item {
  transition: all 0.3s ease; /* Smooth transition for item resizing */
  display: flex;
  justify-content: center; /* Center card if it hits max-width */
}

.platform-card {
  border: 1px solid var(--color-border);
  width: 100%;
  min-width: 280px; /* Requirement 4 */
  max-width: 350px; /* Requirement 4 */
  transition: width 0.3s ease, transform 0.3s ease;
}

.card-header {
  display: flex;
  align-items: center;
  padding: 10px 16px;
  background-color: var(--color-surface-muted);
  border-bottom: 1px solid var(--color-border);
}

.platform-icon {
  width: 24px;
  height: 24px;
  margin-right: 10px;
  border-radius: 4px;
}

.platform-name {
  font-weight: bold;
  font-size: 16px;
}

.spacer {
  flex: 1;
}

.card-body {
  padding: 16px;
}

.status-area {
  min-height: 40px;
  margin-top: 8px;
}

.message {
  margin-top: 8px;
  font-size: 14px;
  color: var(--color-success);
  text-align: center;
}

.message.error {
  color: var(--color-error);
}

/* Transition for stats panel */
.slide-down-enter-active,
.slide-down-leave-active {
  transition: all 0.3s ease;
}

.slide-down-enter-from,
.slide-down-leave-to {
  transform: translateY(-20px);
  opacity: 0;
}
</style>
